name: coinseek
description: "DragonHack 2024 app entry"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management & Routing
  go_router: ^13.2.1
  flutter_riverpod: ^2.4.2
  riverpod_annotation: ^2.1.6

  # Logic & Utils
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  http: ^1.2.1
  flutter_cache_manager: ^3.3.1
  async: ^2.11.0
  path: ^1.9.0

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  sliding_up_panel: ^2.0.0+1

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2

  # Location
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.1
  pixelarticons: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  hive_generator:
  custom_lint:
  riverpod_generator: 3.0.0-dev.3
  riverpod_lint: ^2.2.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/
    - assets/markers/
    - assets/icons/